export enum MissionHistorique {
    NOUVELLE_MISSION = "NOUVELLE_MISSION",
    AJOUT_MEMBRE = "AJOUT_MEMBRE",
    NOUVEAU_DOCUMENT = "NOUVEAU_DOCUMENT",
    NOUVELLE_VERSION = "NOUVELLE_VERSION",
    RETRAIT_MEMBRE = "RETRAIT_MEMBRE",
    SUPPRESSION_DOCUMENT = "SUPPRESSION_DOCUMENT",
}