create type "public"."phase_type" as enum ('prospection', 'contractuelle', 'bon-commande', 'cloture');
create table "public"."missions_phases" (
    "id" bigint generated by default as identity not null,
    "id_mission" bigint not null,
    "type" phase_type not null default 'bon-commande'::phase_type,
    "created_at" timestamp with time zone default now()
);

alter table "public"."missions_phases" enable row level security;
CREATE UNIQUE INDEX missions_phases_pkey ON public.missions_phases USING btree (id);
alter table "public"."missions_phases" add constraint "missions_phases_pkey" PRIMARY KEY using index "missions_phases_pkey";
alter table "public"."missions_phases" add constraint "missions_phases_id_mission_fkey" FOREIGN KEY (id_mission) REFERENCES missions(id) ON DELETE CASCADE not valid;
alter table "public"."missions_phases" validate constraint "missions_phases_id_mission_fkey";