name: Vue

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile && pnpm --dir frontend/ install --frozen-lockfile
      - run: pnpm --dir frontend/ lint
      - run: pnpm --dir frontend/ test:unit --run